### ISSUE TITLE
Add link to medium post in repo

### ISSUE THREAD

**Issue by patcon** [davidrubinger/slack-analysis-medium-post#1]
For those who come to this from the code side and want to find the article :)

https://medium.com/@david.rubinger/4-things-i-learned-about-workplace-communication-from-slack-81329a83ceba

Could be put in two places:
- repo url
- readme

**Comment by davidrubinger** [comment]
Thanks! How would I put the link in the repo URL?

**Comment by patcon** [comment]
Heh just clicking edit beside the repo description on it's front page :)
